name: Lisflood Utilities Unit Tests

on: [push]

jobs:
  tests:
    runs-on: ubuntu-20.04
    strategy:
      max-parallel: 5

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.7
      uses: actions/setup-python@v3
      with:
        python-version: '3.7'
    - name: Install gdal libs
      run: |
        sudo apt-get install libgdal-dev gdal-bin
        export CPLUS_INCLUDE_PATH=/usr/include/gdal
        export C_INCLUDE_PATH=/usr/include/gdal
        # check gdal version with 
        gdal-config --version
        GDAL_VERSION=`gdal-config --version`
    - name: Add conda to system path
      run: |
        # $CONDA is an environment variable pointing to the root of the miniconda directory
        echo $CONDA/bin >> $GITHUB_PATH
    - name: Install PCRASTER
      run: |
        conda install -c conda-forge pcraster=4.4.0
    - name: Install GDAL
      run: |
        conda install -c conda-forge libgdal=$GDAL_VERSION gdal=$GDAL_VERSION
    - name: Install ECCODES
      run: |
        conda install -c conda-forge eccodes=2.28.0
    - name: Install eccodes-python
      run: |
        pip install eccodes-python==0.9.7
    - name: Install pyg2p
      run: |
        pip install pyg2p==3.2.3
    - name: Install requirements
      run: |
        pip install -r requirements.txt
    - name: Test with pytest
      run: |
        conda install pytest
        pytest
